ItemsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.itemsTableName}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
UserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: ${self:custom.cognito.userPoolName}
    UsernameAttributes:
      - email
    AutoVerifiedAttributes:
      - email
    Policies:
      PasswordPolicy:
        MinimumLength: 8
        RequireLowercase: true
        RequireNumbers: true
        RequireSymbols: false
        RequireUppercase: true
UserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    ClientName: ${self:custom.cognito.userPoolClientName}
    UserPoolId:
      Ref: UserPool
    GenerateSecret: false
    ExplicitAuthFlows:
      - ALLOW_USER_PASSWORD_AUTH
      - ALLOW_REFRESH_TOKEN_AUTH
      - ALLOW_USER_SRP_AUTH
    PreventUserExistenceErrors: ENABLED


